# Title: Composer YAML
# Author: Professor Kumar
# Date: Aug 28, 2022
# Modified by: Ferdinand Detres Jr
# Description: API with get and post methods for returning Composer documents
# Validated through Swagger editor

openapi: "3.0.0"
info:
  title: Composer API
  version: "1.0"
paths:
  /composers:
    get:
      tags:
        - Composers
      description: Retrieves all composers within database
      responses:
        "200":
          description: Returns all Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception

    post:
      tags:
        - Composers
      description: Adds new Composer Object to Database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: composer object
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  description: first name of composer
                  type: string
                lastName:
                  description: last name of composer
                  type: string
      responses:
        "200":
          description: Created new composer Object
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception

  /composers/{id}:
    get:
      tags:
        - Composers
      description: Retrieves one composer
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the composer to return
          schema:
            type: string
      responses:
        "200":
          description: Returns one composer
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
